---
# Source: eck-operator/templates/operator-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-system
  labels:
    name: elastic-system
    
    control-plane: elastic-operator
    app.kubernetes.io/version: "1.3.1"
    helm.sh/chart: eck-operator-1.3.1
    app.kubernetes.io/managed-by: Helm
