# Source: argo-workflows/templates/server/server-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: argo-workflows-server
  labels:
    helm.sh/chart: argo-workflows-0.2.6
    app.kubernetes.io/name: argo-workflows-server
    app.kubernetes.io/instance: argo-workflows
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argo-workflows
    app.kubernetes.io/version: "v3.0.7"
spec:
  ports:
  - port: 2746
    targetPort: 2746
  selector:
    app.kubernetes.io/name: argo-workflows-server
    app.kubernetes.io/instance: argo-workflows
  sessionAffinity: None
  type: NodePort
