# Source: kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: fed-master-alertmanager
  namespace: fed
  labels:
    app: kube-prometheus-stack-alertmanager
    
    chart: kube-prometheus-stack-14.5.0
    release: "prometheus-fed-master"
    heritage: "Helm"
spec:
  image: quay.io/prometheus/alertmanager:v0.21.0
  version: v0.21.0
  replicas: 1
  listenLocal: false
  serviceAccountName: fed-master-alertmanager
  externalUrl: http://fed-master-alertmanager.fed:9093
  nodeSelector:
    taco-lma: enabled
  paused: false
  logFormat: "logfmt"
  logLevel:  "info"
  retention: "2h"
  alertmanagerConfigSelector: {}
  alertmanagerConfigNamespaceSelector: {}
  routePrefix: "/"
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  portName: web
