# Source: kube-prometheus-stack/templates/prometheus/psp-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fed-master-prometheus-psp
  labels:
    app: kube-prometheus-stack-prometheus
    
    chart: kube-prometheus-stack-14.5.0
    release: "prometheus-fed-master"
    heritage: "Helm"
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - fed-master-prometheus
