
# Source: kube-prometheus-stack/templates/prometheus/prometheus.yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: fed-master-prometheus
  namespace: fed
  labels:
    app: kube-prometheus-stack-prometheus
    
    chart: kube-prometheus-stack-14.5.0
    release: "prometheus-fed-master"
    heritage: "Helm"
spec:
  alerting:
    alertmanagers:
      - namespace: fed
        name: fed-master-alertmanager
        port: web
        pathPrefix: "/"
        apiVersion: v2
  image: quay.io/prometheus/prometheus:v2.24.0
  version: v2.24.0
  externalLabels:
    taco_cluster: federation-master
  externalUrl: http://fed-master-prometheus.fed:9090
  nodeSelector:
    taco-lma: enabled
  paused: false
  replicas: 1
  shards: 1
  logLevel:  info
  logFormat:  logfmt
  listenLocal: false
  enableAdminAPI: false
  retention: "10d"
  routePrefix: "/"
  serviceAccountName: fed-master-prometheus
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector:
    matchLabels:
      name: fed

  podMonitorSelector: {}
  podMonitorNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: "prometheus-fed-master"

  probeNamespaceSelector: {}
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  ruleNamespaceSelector:
    matchLabels:
      name: fed

  ruleSelector: {}
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: rbd
  portName: web

