# Source: kube-prometheus-stack/templates/alertmanager/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fed-master-alertmanager
  namespace: fed
  labels:
    app: kube-prometheus-stack-alertmanager
    self-monitor: "true"
    
    chart: kube-prometheus-stack-14.5.0
    release: "prometheus-fed-master"
    heritage: "Helm"
spec:
  ports:
  - name: web
    port: 9093
    targetPort: 9093
    protocol: TCP
  selector:
    app: alertmanager
    alertmanager: fed-master-alertmanager
  type: "ClusterIP"
