
# Source: thanos/templates/query-frontend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query-frontend
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-3.4.0
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: query-frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos
      app.kubernetes.io/instance: thanos
      app.kubernetes.io/component: query-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos
        helm.sh/chart: thanos-3.4.0
        app.kubernetes.io/instance: thanos
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: query-frontend
    spec:
      
      serviceAccount: thanos-query-frontend
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: thanos
                    app.kubernetes.io/instance: thanos
                    app.kubernetes.io/component: query-frontend
                namespaces:
                  - fed
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      nodeSelector:
        taco-lma: enabled
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: query-frontend
          image: docker.io/bitnami/thanos:0.17.2-scratch-r1
          imagePullPolicy: "IfNotPresent"
          args:
            - query-frontend
            - --log.level=info
            - --http-address=0.0.0.0:10902
            - --query-frontend.downstream-url=http://thanos-query:9090
          ports:
            - name: http
              containerPort: 10902
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            limits: {}
            requests: {}
          volumeMounts:
      volumes:

