# Source: servicemesh-portal/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: servicemesh-portal-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: servicemesh-portal
  namespace: istio-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
