# Source: lma-addons/templates/grafana-dashboard/configmaps-datasources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: lma
  labels:
    grafana_datasource: "1"
    app: grafana
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://fed-master-prometheus:9090/
      access: proxy
      isDefault: true
