# Source: lma-addons/templates/metricbeat/cm-metricbeat.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-config
  labels:
    k8s-app: metricbeat
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      # Mounted `metricbeat-daemonset-modules` configmap:
      path: /usr/share/metricbeat/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: false

    metricbeat.modules:
      - module: prometheus
        metricsets: ['query']
        period: 30s
        hosts: [thanos-query-frontend.fed.svc.cluster.local:9090]
        paths: 
        - name: 'metrics_total_count'
          path: '/api/v1/query'
          fields:
            'query': 'count(up)by(taco_cluster)'
        - name: 'metrics_up_count'
          path: '/api/v1/query'
          fields:
            'query': 'sum(up)by(taco_cluster)'
        - name: 'kubernetes_total_count'
          path: '/api/v1/query'
          fields:
            'query': 'count(up{job=~".*kube.*"})by(taco_cluster)'
        - name: 'kubernetes_up_count'
          path: '/api/v1/query'
          fields:
            'query': 'sum(up{job=~".*kube.*"})by(taco_cluster)'
        - name: 'ceph_total_count'
          path: '/api/v1/query'
          fields:
            'query': 'count(up{job=~".*ceph.*"})by(taco_cluster)'
        - name: 'ceph_up_count'
          path: '/api/v1/query'
          fields:
            'query': 'count(up{job=~".*ceph.*"})by(taco_cluster)'
        - name: 'openstack_total_count'
          path: '/api/v1/query'
          fields:
            'query': 'count(up{job=~".*openstack.*"})by(taco_cluster)'
        - name: 'openstack_up_count'
          path: '/api/v1/query'
          fields:
            'query': 'sum(up{job=~".*openstack.*"})by(taco_cluster)'
        - name: 'openstack_libvirt_up'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_mariadb_up'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_rabbitmq_up'
          path: '/api/v1/query'
          fields:
            'query': 'sum(rabbitmq_up)by(taco_cluster)'
        - name: 'openstack_memcached_up'
          path: '/api/v1/query'
          fields:
            'query': 'sum(memcached_up)by(taco_cluster)'
        - name: 'openstack_keystone_up'
          path: '/api/v1/query'
          fields:
            'query': 'sum(openstack_check_keystone_api)by(taco_cluster)'
        - name: 'openstack_nova_up'
          path: '/api/v1/query'
          fields:
            'query': 'sum(openstack_check_nova_api)by(taco_cluster)'
        - name: 'openstack_neutron_up'
          path: '/api/v1/query'
          fields:
            'query': 'sum(openstack_check_neutron_api)by(taco_cluster)'
        - name: 'openstack_cinder_up'
          path: '/api/v1/query'
          fields:
            'query': 'sum(openstack_check_cinder_api)by(taco_cluster)'
        - name: 'openstack_glance_up'
          path: '/api/v1/query'
          fields:
            'query': 'sum(openstack_check_glance_api)by(taco_cluster)'
        - name: 'openstack_heat_up'
          path: '/api/v1/query'
          fields:
            'query': 'sum(openstack_check_heat_api)by(taco_cluster)'
        - name: 'openstack_horizon_up'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_libvirt_requests_total'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_libvirt_requests_ok'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_mariadb_requests_total'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_mariadb_requests_ok'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_rabbitmq_requests_total'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_rabbitmq_requests_ok'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_keystone_requests_total'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_keystone_requests_ok'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_nova_requests_total'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_nova_requests_ok'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_neutron_requests_total'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_neutron_requests_ok'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_cinder_requests_total'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_cinder_requests_ok'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_glance_requests_total'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_glance_requests_ok'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_heat_requests_total'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_heat_requests_ok'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_horizon_requests_total'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_horizon_requests_ok'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_project_total'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_user_total'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_instance_total'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_volume_total'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'openstack_image_total'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(1),"taco_cluster","main","taco_cluster",".*")'
        - name: 'ceph_health_status'
          path: '/api/v1/query'
          fields:
            'query': 'ceph_health_status'
        - name: 'ceph_mon_total'
          path: '/api/v1/query'
          fields:
            'query': 'count(ceph_mon_quorum_status)by(taco_cluster)'
        - name: 'ceph_mon_up'
          path: '/api/v1/query'
          fields:
            'query': 'sum(ceph_mon_quorum_status)by(taco_cluster)'
        - name: 'ceph_mgr_up'
          path: '/api/v1/query'
          fields:
            'query': 'sum(ceph_mgr_status)by(taco_cluster)'
        - name: 'ceph_mgr_total'
          path: '/api/v1/query'
          fields:
            'query': 'count(ceph_mgr_metadata)by(taco_cluster)'
        - name: 'ceph_mds_total'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(0),"taco_cluster","main","taco_cluster",".*")'
        - name: 'ceph_mds_up'
          path: '/api/v1/query'
          fields:
            'query': 'label_replace(vector(0),"taco_cluster","main","taco_cluster",".*")'
        - name: 'ceph_osd_total'
          path: '/api/v1/query'
          fields:
            'query': 'count(ceph_osd_in)by(taco_cluster)'
        - name: 'ceph_osd_down'
          path: '/api/v1/query'
          fields:
            'query': 'count(ceph_osd_metadata)by(taco_cluster)-count(ceph_osd_in)by(taco_cluster)'
        - name: 'ceph_osd_out'
          path: '/api/v1/query'
          fields:
            'query': 'count(ceph_osd_metadata)by(taco_cluster)-count(ceph_osd_in)by(taco_cluster)'
        - name: "ceph_osd_usage"
          path: "/api/v1/query"
          fields:
            'query': 'sum(ceph_osd_stat_bytes_used)by(taco_cluster)/sum(ceph_osd_stat_bytes)by(taco_cluster)*100'
        - name: "ceph_osd_in"
          path: "/api/v1/query"
          fields:
            'query': 'sum(ceph_osd_in)by(taco_cluster)'
        - name: 'ceph_osd_down'
          path: '/api/v1/query'
          fields:
            'query': 'count(ceph_osd_metadata)by(taco_cluster)-count(ceph_osd_up)by(taco_cluster)'
        - name: 'ceph_total_objects'
          path: '/api/v1/query'
          fields:
            'query': 'sum(ceph_pool_objects)by(taco_cluster)'
        - name: 'ceph_objects_delta_1d'
          path: '/api/v1/query'
          fields:
            'query': 'round(sum(delta(ceph_pool_objects[1d]))by(taco_cluster))'
        - name: 'ceph_total_bytes'
          path: '/api/v1/query'
          fields:
            'query': 'sum(ceph_cluster_total_bytes)by(taco_cluster)'
        - name: 'ceph_total_used_bytes'
          path: '/api/v1/query'
          fields:
            'query': 'sum(ceph_cluster_total_used_bytes)by(taco_cluster)'
        - name: 'ceph_pool_usage'
          path: '/api/v1/query'
          fields:
            'query': '(ceph_pool_stored)*on(pool_id)group_left(name)(ceph_pool_metadata)'
        - name: 'node_total_count'
          path: '/api/v1/query'
          fields:
            'query': 'count(count(kube_node_info)by(node,taco_cluster))by(taco_cluster)'
        - name: 'dockerd_up'
          path: '/api/v1/query'
          fields:
            'query': 'count(namedprocess_namegroup_states{groupname="dockerd",state=~"Sleeping|Running",namespace="lma"}>0)by(taco_cluster)'
        - name: 'dockerd_down'
          path: '/api/v1/query'
          fields:
            'query': 'count(count(kube_node_info)by(node,taco_cluster))by(taco_cluster)-count(namedprocess_namegroup_states{groupname="dockerd",state=~"Sleeping|Running",namespace="lma"}>0)by(taco_cluster)'
        - name: 'mem_usage'
          path: '/api/v1/query'
          fields:
            'query': 'sum((node_memory_MemTotal_bytes-node_memory_MemFree_bytes)/node_memory_MemFree_bytes)by(taco_cluster)'
        - name: 'node'
          path: '/api/v1/query'
          fields:
            'query': 'kube_node_labels[1m]'
        - name: 'namespace'
          path: '/api/v1/query'
          fields:
            'query': 'count(kube_pod_info)by(namespace,taco_cluster)'
        - name: 'pod_total'
          path: '/api/v1/query'
          fields:
            'query': 'sum(kube_pod_status_phase)by(namespace,taco_cluster)'
        - name: 'pod_running'
          path: '/api/v1/query'
          fields:
            'query': 'sum(kube_pod_status_phase{phase="Running"})by(namespace,taco_cluster)'
        - name: 'pod_error'
          path: '/api/v1/query'
          fields:
            'query': 'sum(kube_pod_status_phase{phase=~"Failed|Unknown"})by(namespace,taco_cluster)'
        - name: 'pod_pending'
          path: '/api/v1/query'
          fields:
            'query': 'sum(kube_pod_status_phase{phase=~"Pending"})by(namespace,taco_cluster)'
        - name: 'network_throughput'
          path: '/api/v1/query'
          fields:
            'query': 'topk(3,rate(node_network_receive_bytes_total[3m])+rate(node_network_transmit_bytes_total[3m]))by(taco_cluster)'
        - name: 'network_rx'
          path: '/api/v1/query'
          fields:
            'query': 'topk(3,rate(node_network_receive_bytes_total[3m]))by(taco_cluster)'
        - name: 'network_tx'
          path: '/api/v1/query'
          fields:
            'query': 'topk(3,rate(node_network_transmit_bytes_total[3m]))by(taco_cluster)'
        - name: 'pod_cpu'
          path: '/api/v1/query'
          fields:
            'query': 'topk(3,sum(rate(container_cpu_user_seconds_total{pod!~""}[3m]))by(taco_cluster,pod))by(taco_cluster)'
        - name: 'coreDNS_total'
          path: '/api/v1/query'
          fields:
            'query': 'count(coredns_build_info)by(taco_cluster)'
        - name: 'coreDNS_up'
          path: '/api/v1/query'
          fields:
            'query': 'count(coredns_build_info==1)by(taco_cluster)'
        - name: 'coreDNS_down'
          path: '/api/v1/query'
          fields:
            'query': 'count(coredns_build_info==0)by(taco_cluster) or vector(0)'
        - name: 'scheduler_total'
          path: '/api/v1/query'
          fields:
            'query': 'count(up{job="kube-scheduler"})by(taco_cluster)'
        - name: 'scheduler_up'
          path: '/api/v1/query'
          fields:
            'query': 'count(up{job="kube-scheduler"}==1)by(taco_cluster)'
        - name: 'scheduler_down'
          path: '/api/v1/query'
          fields:
            'query': 'count(up{job="kube-scheduler"}==0)by(taco_cluster) or vector(0)'
        - name: 'apiserver_total'
          path: '/api/v1/query'
          fields:
            'query': 'count(up{job="apiserver"})by(taco_cluster)'
        - name: 'apiserver_up'
          path: '/api/v1/query'
          fields:
            'query': 'count(up{job="apiserver"}==1)by(taco_cluster)'
        - name: 'apiserver_down'
          path: '/api/v1/query'
          fields:
            'query': 'count(up{job="apiserver"}==0)by(taco_cluster) or vector(0)'
        - name: 'proxy_total'
          path: '/api/v1/query'
          fields:
            'query': 'count(up{job="kube-proxy"})by(taco_cluster)'
        - name: 'proxy_up'
          path: '/api/v1/query'
          fields:
            'query': 'count(up{job="kube-proxy"}==1)by(taco_cluster) or vector(0)'
        - name: 'proxy_down'
          path: '/api/v1/query'
          fields:
            'query': 'count(up{job="kube-proxy"}==0)by(taco_cluster) or vector(0)'
        - name: 'alert_total_count'
          path: '/api/v1/query'
          fields:
            'query': 'sum(ALERTS)by(taco_cluster) or vector(0)'
        - name: 'alert_page_count'
          path: '/api/v1/query'
          fields:
            'query': 'sum(ALERTS{severity="page"})by(taco_cluster) or vector(0)'
        - name: 'alert_critical_count'
          path: '/api/v1/query'
          fields:
            'query': 'sum(ALERTS{severity="critical"})by(taco_cluster) or vector(0)'
        - name: 'alert_warning_count'
          path: '/api/v1/query'
          fields:
            'query': 'sum(ALERTS{severity="warning"})by(taco_cluster) or vector(0)'
        - name: 'alert_1d_count'
          path: '/api/v1/query'
          fields:
            'query': 'sum(changes(ALERTS_FOR_STATE[1d]))by(taco_cluster)'
        - name: 'alert_1w_count'
          path: '/api/v1/query'
          fields:
            'query': 'sum(changes(ALERTS_FOR_STATE[1w]))by(taco_cluster)'
        - name: 'alert_15d_count'
          path: '/api/v1/query'
          fields:
            'query': 'sum(changes(ALERTS_FOR_STATE[15d]))by(taco_cluster)'
        - name: 'alert'
          path: '/api/v1/query'
          fields:
            'query': 'sum(changes(ALERTS_FOR_STATE[1h])!=0)by(taco_cluster,severity,alertname,job)'
        - name: 'top3_restart_pod'
          path: '/api/v1/query'
          fields:
            'query': 'topk(3,kube_pod_container_status_restarts_total)by(taco_cluster)'
        - name: "etcd_total"
          path: '/api/v1/query'
          fields:
            'query': 'count(etcd_server_has_leader)by(taco_cluster)'
        - name: "etcd_up"
          path: '/api/v1/query'
          fields:
            'query': 'sum(etcd_server_has_leader)by(taco_cluster)'
        - name: "etcd_down"
          path: '/api/v1/query'
          fields:
            'query': 'count(etcd_server_has_leader==0)by(taco_cluster) or vector(0)'
        - name: "cpu_usage"
          path: '/api/v1/query'
          fields:
            'query': 'sum(rate(node_cpu_seconds_total{mode!~"idle|iowait"}[1m]))by(taco_cluster)'
        - name: "up"
          path: '/api/v1/query'
          fields:
            'query': 'up[1m]'
    logging.level: info
    # output configuration
    output.elasticsearch:
      hosts: 
      - https://eck-elasticsearch-es-http.lma.svc.cluster.local:9200
      username: elastic
      password: tacoword
      ssl.verification_mode: none
