# Source: fluentbit-operator/templates/fluentbit/fluentbit.yaml
apiVersion: logging.kubesphere.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  namespace: lma
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: v1.4.5
spec:
  image: "siim/fluent-bit-for-operator:v1.4.6"
  positionDB:
    hostPath:
      path: /var/log/flb_kube.db
      type: FileOrCreate
  fluentBitConfigName: fluent-bit-config
  containerLogRealPath: /var/lib/docker/containers
