# Source: kube-prometheus-stack/templates/alertmanager/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fed-master-alertmanager
  namespace: lma
  labels:
    app: kube-prometheus-stack-alertmanager
    
    chart: kube-prometheus-stack-14.5.0
    release: "prometheus-fed-master"
    heritage: "Helm"
imagePullSecrets:
  []
