# Source: eck-operator/templates/webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "elastic-webhook-server-cert"
  namespace: elastic-system
  labels:
    
    app.kubernetes.io/name: elastic-operator
    app.kubernetes.io/instance: eck-operator
    app.kubernetes.io/version: "1.3.1"
    helm.sh/chart: eck-operator-1.3.1
    app.kubernetes.io/managed-by: Helm
