
# Source: kube-prometheus-stack/templates/prometheus-operator/psp-clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-operator-operator-psp
  labels:
    app: kube-prometheus-stack-operator
    
    chart: kube-prometheus-stack-14.5.0
    release: "prometheus-operator"
    heritage: "Helm"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator-operator-psp
subjects:
  - kind: ServiceAccount
    name: prometheus-operator-operator
    namespace: lma

