# Source: kube-prometheus-stack/templates/prometheus-operator/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator-operator
  namespace: lma
  labels:
    app: kube-prometheus-stack-operator
    
    chart: kube-prometheus-stack-14.5.0
    release: "prometheus-operator"
    heritage: "Helm"
spec:
  endpoints:
  - port: https
    scheme: https
    tlsConfig:
      serverName: prometheus-operator-operator
      ca:
        secret:
          name: prometheus-operator-admission
          key: ca
          optional: false
    honorLabels: true
  selector:
    matchLabels:
      app: kube-prometheus-stack-operator
      release: "prometheus-operator"
  namespaceSelector:
    matchNames:
      - "lma"
