# Source: prepare-etcd-secret/templates/job-secret.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: prepare-etcd-secret
spec:
  template:
    metadata:
      name: prepare-etcd-secret
    spec:
      serviceAccountName: prepare-etcd-secret
      containers:
      - name: hyperkube
        image: "k8s.gcr.io/hyperkube:v1.18.8"
        imagePullPolicy: IfNotPresent
        command:
        - /bin/bash
        - -c
        - |
          kubectl create secret generic etcd-client-cert \
          --from-file=etcd-ca=/ssl/ca.crt \
          --from-file=etcd-client=/ssl/peer.crt \
          --from-file=etcd-client-key=/ssl/peer.key \
          --namespace lma
        volumeMounts:
        - name: ssldir
          mountPath: /ssl
      volumes:
      - name: ssldir
        hostPath:
          path: /etc/kubernetes/pki/etcd
          type: Directory
      restartPolicy: OnFailure

