# Source: lma-addons/templates/service-monitor/federations.yaml
apiVersion: v1
kind: Service
metadata:
  name: dev-federate
  namespace: lma
  labels:
    app: dev-federate
spec:
  ports:
  - name: metrics 
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    prometheus: lma-prometheus
