# Source: jaeger-operator/templates/jaeger.yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-operator-jaeger
  namespace: lma
spec:
  agent:
    strategy: Sidecar
  collector:
    maxReplicas: 5
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
  ingress:
    enabled: false
  query:
    replicas: 1
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
  storage:
    esIndexCleaner:
      enabled: true
      numberOfDays: 7
      schedule: 55 04 * * *
    options:
      es:
        index-prefix: jaeger
        password: TO_BE_FIXED
        server-urls: TO_BE_FIXED
        tls.ca: /etc/ssl/certs/tls.crt
        username: TO_BE_FIXED
    type: elasticsearch
  strategy: production
  volumeMounts:
  - mountPath: /etc/ssl/certs
    name: es-tls
  volumes:
  - name: es-tls
    secret:
      secretName: eck-elasticsearch-es-http-certs-public

