
# Source: kube-prometheus-stack/templates/prometheus-operator/psp-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-operator-operator-psp
  labels:
    app: kube-prometheus-stack-operator
    
    chart: kube-prometheus-stack-14.5.0
    release: "prometheus-operator"
    heritage: "Helm"
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - prometheus-operator-operator

