
# Source: kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name:  prometheus-operator-admission-create
  namespace: lma
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: kube-prometheus-stack-admission-create    
    chart: kube-prometheus-stack-14.5.0
    release: "prometheus-operator"
    heritage: "Helm"
spec:
  template:
    metadata:
      name:  prometheus-operator-admission-create
      labels:
        app: kube-prometheus-stack-admission-create        
        chart: kube-prometheus-stack-14.5.0
        release: "prometheus-operator"
        heritage: "Helm"
    spec:
      containers:
        - name: create
          image: jettech/kube-webhook-certgen:v1.5.0
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host=prometheus-operator-operator,prometheus-operator-operator.lma.svc
            - --namespace=lma
            - --secret-name=prometheus-operator-admission
          resources:
            {}
      restartPolicy: OnFailure
      serviceAccountName: prometheus-operator-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000

