
# Source: taco-watcher/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: taco-watcher
  labels:
    app.kubernetes.io/name: taco-watcher
    helm.sh/chart: taco-watcher-0.1.0
    app.kubernetes.io/instance: taco-watcher
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 32000
      targetPort: http
      nodePort: 32000
      protocol: TCP
      name: http
    - port: 32001
      targetPort: 32001
      nodePort: 32001
      protocol: TCP
      name: http-32001
    - port: 32002
      targetPort: 32002
      nodePort: 32002
      protocol: TCP
      name: http-32002
    - port: 32003
      targetPort: 32003
      nodePort: 32003
      protocol: TCP
      name: http-32003
    - port: 32004
      targetPort: 32004
      nodePort: 32004
      protocol: TCP
      name: http-32004
    - port: 32005
      targetPort: 32005
      nodePort: 32005
      protocol: TCP
      name: http-32005
    - port: 32006
      targetPort: 32006
      nodePort: 32006
      protocol: TCP
      name: http-32006
    - port: 32007
      targetPort: 32007
      nodePort: 32007
      protocol: TCP
      name: http-32007
    - port: 32008
      targetPort: 32008
      nodePort: 32008
      protocol: TCP
      name: http-32008
  selector:
    app.kubernetes.io/name: taco-watcher
    app.kubernetes.io/instance: taco-watcher

