
# Source: kube-prometheus-stack/templates/prometheus/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lma-prometheus
  labels:
    app: kube-prometheus-stack-prometheus
    
    chart: kube-prometheus-stack-14.5.0
    release: "prometheus"
    heritage: "Helm"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lma-prometheus
subjects:
  - kind: ServiceAccount
    name: lma-prometheus
    namespace: lma

