# Source: kube-prometheus-stack/templates/prometheus/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lma-prometheus
  namespace: lma
  labels:
    app: kube-prometheus-stack-prometheus
    
    chart: kube-prometheus-stack-14.5.0
    release: "prometheus"
    heritage: "Helm"
imagePullSecrets:
  []
