# Source: kube-prometheus-stack/templates/prometheus/serviceThanosSidecar.yaml
apiVersion: v1
kind: Service
metadata:
  name: lma-thanos-discovery
  namespace: lma
  labels:
    app: kube-prometheus-stack-thanos-discovery
    
    chart: kube-prometheus-stack-14.5.0
    release: "prometheus"
    heritage: "Helm"
spec:
  type: NodePort
  clusterIP: 
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
    nodePort: 30901
  selector:
    app: prometheus
    prometheus: lma-prometheus
