# Source: eck-operator/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-operator
  namespace: elastic-system
  labels:
    
    control-plane: elastic-operator
    app.kubernetes.io/version: "1.3.1"
    helm.sh/chart: eck-operator-1.3.1
    app.kubernetes.io/managed-by: Helm
